name: Build and Deploy to aws-lambda

on:
  workflow_dispatch:
    inputs:
      checked:
        description: 'did lambda function code got updated from aws-console'     
        required: true
        default: false

jobs:
  Deploy:
    name: 'Installing, Ziping, and Deploying Function'
    runs-on: ubuntu-latest
    environment: production

    if (github.event.inputs.environment) ; then
      steps:
        - uses: actions/checkout@v2

        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '14.x'

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: "Installing, and Deploying Function"
          run: |
            cd lambdas
            pwd
            for fun in html-to-pdf ; do
              cd ${fun}

              if [[ -f "index.js" ]]; then
                zip -j deploy.zip ./*
                aws lambda update-function-code --function-name=${fun} --zip-file=fileb://deploy.zip
              fi
              
              cd ..
            done
    fi